import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import PageLayout from '@/components/PageLayout/PageLayout'
import Chatbot from '@/components/Chatbot/Chatbot'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PageLayout>{children}</PageLayout>
        <Chatbot />
      </body>
    </html>
  )
}
